name: Execute python app

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Enable debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python api/fetch_price_data_with_api.py

      # - name: Create and set up virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      #     pip install --upgrade pip
      #     if [ -f requirements.txt ]; then
      #       pip install -r requirements.txt
      #     else
      #       echo "No requirements.txt found, skipping installation."
      #     fi
      #     python api/fetch_price_data_with_api.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${GITHUB_WORKFLOW_ID}
          include-hidden-files: true
          path: |
            ${{ github.workspace }}/**/*.csv
            ${{ github.workspace }}/**/output.xlsx
