name: Execute python app

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create and set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping installation."
          fi
          python api/fetch_price_data_with_api.py

    #   - name: Execute Python script
    #     run: |
    #       source venv/bin/activate
    #       python api/fetch_price_data_with_api.py

      - name: Commit and push output files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add all_fund_profit_percentages_api.csv all_fund_prices_api.csv || echo "No files to commit"
          git commit -m "Update output files from fetch_price_data_with_api.py" || echo "Nothing to commit"
          git push origin main          