name: Execute python app

on:
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Enable debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python api/async.py

      - name: execute py-excel script
        run: python api/excel_writer.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${GITHUB_WORKFLOW_ID}
          include-hidden-files: true
          path: |
            ${{ github.workspace }}/**/*.csv
            ${{ github.workspace }}/**/output.xlsx
