name: Execute python app

on:
  schedule:
    - cron: '0 17 * * 1-5'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Enable debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python api/async.py

      - name: execute py-excel script
        run: python api/excel_writer.py

      - name: Set DATETIME env
        run: echo "DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DATETIME }}_UTC+000_${{ github.run_id }}
          include-hidden-files: true
          path: |
            ${{ github.workspace }}/**/*.csv
            ${{ github.workspace }}/**/output.xlsx
